##
## You provide this
##
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: database-updater
spec:
  selector:
    matchLabels:
      app: database-updater
  replicas: 1
  template:
    metadata:
      labels:
        app: database-updater
    spec:
      containers:
      - name: database-updater
        image: msech/database-updater
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
        env:
          - name: RABBITMQ_HOST
            value: 'rabbitmq'
          - name: REDIS_HOST
            value: 'redis'