##
## You provide this
##
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: redis-lookup
spec:
  selector:
    matchLabels:
      app: redis-lookup
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-lookup
    spec:
      containers:
      - name: redis-lookup
        image: msech/redis-lookup
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
        ports:
        - containerPort: 5000
        env:
          - name: RABBITMQ_HOST
            value: 'rabbitmq'
          - name: REDIS_HOST
            value: 'redis'